version: '2'

services:
  nginx:
    image: nginx:1.11.9
    volumes_from:
      - api
    depends_on:
      - api
    ports:
      - 80:80

  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis_db:
    image: 'redis:3.2-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  api:
    depends_on:
      - 'postgres'
      - 'redis_db'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './:/var/www/citibike_planner_api'
      - nginx_config:/etc/nginx/conf.d
    env_file:
      - '.env'

  worker:
    command: bundle exec rake resque:work RAILS_ENV=development QUEUE='*'
    depends_on:
      - 'postgres'
      - 'redis_db'
    build: .
    volumes:
      - './:/var/www/citibike_planner_api'
      - nginx_config:/etc/nginx/conf.d
    env_file:
      - '.env'

  scheduler:
    command: bundle exec rake resque:scheduler
    depends_on:
      - 'postgres'
      - 'redis_db'
    build: .
    ports:
      - '5678:5678'
    volumes:
      - './:/var/www/citibike_planner_api'
      - nginx_config:/etc/nginx/conf.d
    env_file:
      - '.env'

  scheduler_web:
    command: bundle exec resque-web config/initializers/resque.rb
    depends_on:
      - 'postgres'
      - 'redis_db'
    build: .
    volumes:
      - './:/var/www/citibike_planner_api'
      - nginx_config:/etc/nginx/conf.d
    env_file:
      - '.env'
      

volumes:
  redis:
  postgres:
  nginx_config:
    external: false
